### ISSUE TITLE
`azurerm_monitor_diagnostic_setting.metric.enabled/retention_policy.days` still has changed after apply

### ISSUE THREAD

**Issue by shu-ying789** [ms-henglu/azurerm-provider-issues#10]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* `terraform v1.1.2 on windows_amd64`
* `azurerm v2.96.0`

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-40"
  location = "West Europe"
}

resource "azurerm_storage_account" "test" {
  name                     = "acctest40"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_replication_type = "LRS"
  account_tier             = "Standard"
}

resource "azurerm_key_vault" "test" {
  name                = "acctest40"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"
}

resource "azurerm_monitor_diagnostic_setting" "test" {
  name               = "acctest-DS-40"
  target_resource_id = azurerm_key_vault.test.id
  storage_account_id = azurerm_storage_account.test.id

  log {
    category = "AuditEvent"
    enabled  = false

    retention_policy {
      enabled = false
    }
  }

  metric {
    category = "AllMetrics"
    enabled  = true
    retention_policy {
      enabled = false
      days    = 7
    }
  }
}
```

### Debug Output

![monitor_diagnostic1](https://user-images.githubusercontent.com/96756505/155466528-3e247005-c9f2-483e-af76-7615fd99d7d6.png)
![dia2](https://user-images.githubusercontent.com/96756505/155466534-59c25757-7ea6-48f8-9e31-22abc5d3e58f.png)

### Expected Behaviour

do plan after apply dones have no changes
### Actual Behaviour
do plan after apply done still have changes

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. `terraform plan`

### References

* #0000

**Comment by ms-henglu** [comment]
@shu-ying789 , try this
```
resource "azurerm_monitor_diagnostic_setting" "test" {
  name               = "henglu-DS-40"
  target_resource_id = azurerm_key_vault.test.id
  storage_account_id = azurerm_storage_account.test.id

  log {
    category = "AuditEvent"
    enabled  = false

    retention_policy {
      enabled = false
    }
  }

  log {
    category = "AzurePolicyEvaluationDetails"
    enabled  = false

    retention_policy {
      enabled = false
    }
  }

  metric {
    category = "AllMetrics"
    enabled  = true
    retention_policy {
      enabled = false
      days    = 7
    }
  }
}

```
