### ISSUE TITLE
`azurerm_batch_pool.start_task.user_identity.user_name` user_name and auto_user blocks can be used both at the same time

### ISSUE THREAD

**Issue by shu-ying789** [ms-henglu/azurerm-provider-issues#13]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* `terraform v1.1.2 on windows_amd64`
*  `azurerm v2.96.0`

### Affected Resource(s)

* `azurerm_batch_pool

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "testaccRG-batch-22shu"
  location = "West Europe"
}

resource "azurerm_batch_account" "test" {
  name                = "testaccbatch22shu"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
}

resource "azurerm_batch_pool" "test" {
  name                = "testaccpool22shu"
  resource_group_name = azurerm_resource_group.test.name
  account_name        = azurerm_batch_account.test.name
  node_agent_sku_id   = "batch.node.ubuntu 18.04"
  vm_size             = "Standard_A1"

  fixed_scale {
    target_dedicated_nodes = 1
  }

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "18.04-lts"
    version   = "latest"
  }

  start_task {
    command_line       = "echo 'Hello World from $env'"
    wait_for_success   = true
    task_retry_maximum = 5
    common_environment_properties = {
      env = "TEST"
      bu  = "Research&Dev"
    }

    user_identity {
      user_name = "username"  
      auto_user {
        elevation_level = "NonAdmin"
        scope           = "Task"
      }
    }

    resource_file {
      storage_container_url = "https://raw.githubusercontent.com/hashicorp/terraform-provider-azurerm/main/README.md"
      file_path             = "README.md"
    }
  }
}
```

### Debug Output

![image](https://user-images.githubusercontent.com/96756505/155684186-fec8b7fb-0cba-4623-a0f0-7a51a7a58d25.png)

### Expected Behaviour

Can define either auto_user or user_name in the user_identity block.

### Actual Behaviour

The user_identity block can only define auto_user, not user_name.
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. `terraform plan`

### References

* #0000

**Comment by ms-henglu** [comment]
@shu-ying789 , I found the bug: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/batch/batch_pool.go#L462

It should be 
```
userIdentityValue["user_name"]
```
instead of `userIdentityValue["username"]`

**Comment by ms-henglu** [comment]
@shu-ying789 , check this fix: https://github.com/ms-henglu/terraform-provider-azurerm/commit/21eb659ccf25fd0fe413c2e7c9642c6b0a3ea89b

**Comment by shu-ying789** [comment]
<img width="789" alt="batch-pool-bug-" src="https://user-images.githubusercontent.com/96756505/165690745-78eba92b-5ff6-486a-bee7-02a78c7393f7.png">
<img width="793" alt="batch-pool-bug-2" src="https://user-images.githubusercontent.com/96756505/165690772-a2186533-8a93-4007-ad2c-5531ad351ad5.png">
