### ISSUE TITLE
`azurerm_app_service.site_config.scm_ip_restriction.service_tag/headers.x_azure_fdid/x_fd_health_probe/x_forwarded_for/x_forwarded_host` still has changed after apply

### ISSUE THREAD

**Issue by shu-ying789** [ms-henglu/azurerm-provider-issues#9]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* `terraform v1.1.2 on windows_amd64`
*  `azurerm v2.96.0`

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
rovider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-91"
  location = "West Europe"
}

resource "azurerm_app_service_plan" "test" {
  name                = "acctestASP-91"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_app_service" "test" {
  name                = "acctestAS-91"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  app_service_plan_id = azurerm_app_service_plan.test.id

  site_config {
    scm_ip_restriction {
      ip_address = "10.10.10.10/32"
      name       = "test-restriction"
      priority   = 123
      action     = "Allow"
      service_tag = "AzureEventGrid"
      headers {
        x_azure_fdid      = ["55ce4ed1-4b06-4bf1-b40e-4638452104da"]
        x_fd_health_probe = ["1"]
        x_forwarded_for   = ["9.9.9.9/32", "2002::1234:abcd:ffff:c0a8:101/64"]
        x_forwarded_host  = ["example.com"]
      }
    }
  }
}
```

### Debug Output

![app1](https://user-images.githubusercontent.com/96756505/155450777-a8674f22-fb8a-4827-9408-1751ed6fa887.png)

![app2](https://user-images.githubusercontent.com/96756505/155450782-2bb86ba7-55e1-488d-9884-806c3d43f86c.png)

### Expected Behaviour

do plan after apply dones have no changes

### Actual Behaviour

do plan after apply done still have changes

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. `terraform plan`

### References

* #0000

**Comment by ms-henglu** [comment]
@shu-ying789  service is deprecated.
